### ISSUE TITLE
Error: Activity not started, unable to resolve Intent

### ISSUE THREAD

**Issue by ajaykumar97** [ReactNativeSchool/react-navigation-deep-linking#1]
I am getting the error message as given below when I do ``adb shell am start -W -a android.intent.action.VIEW -d "exp://127.0.0.1:19004/--/details/3" com.deeplinking``

```
Starting: Intent { act=android.intent.action.VIEW dat=exp://127.0.0.1:19004/--/details/3 pkg=com.deeplinking }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://127.0.0.1:19004/--/details/3 flg=0x10000000 pkg=com.deeplinking }
```

I am using expo on MacOS and an Android device.

**Comment by spencercarli** [comment]
Sorry, I made a typo in the tutorial. To open the android app it should be

```
adb shell am start -W -a android.intent.action.VIEW -d "exp://127.0.0.1:19000/--/details/3"
```

**Comment by ajaykumar97** [comment]
Thanks @spencercarli Its working now.
And thanks a lot for your tutorials and posts. They are really helpful for me to understand the concepts of ReactNative. Keep it up.

**Comment by spencercarli** [comment]
Happy to help!
